config/routes.rb
Rails.application.routes.draw do

  root 'messages#index'

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: 'logout'

  get '/signup' => 'users#new', as: 'signup'
  post '/signup' => 'users#create'

  post '/message' => 'messages#create', as: 'message'

  mount ActionCable.server, at: '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, uniqueness: true, presence: true, length: {minimum: 3, maximum: 15}
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:error] = "You must be logged in to view the page"
      redirect_to login_path
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :require_user

  def index
    @messages = Message.all
    @message = Message.new
  end

  def create
    message = current_user.messages.build(params.require(:message).permit(:body))
    if message.save
      ActionCable.server.broadcast "chatroom_channel", foo: message_render(message)
    end
  end

  private

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_back fallback_location: root_path if logged_in?
  end

  def create
    user ||= User.find_by(username: params[:session][:username])
    if user and user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to root_path
    else
      flash.now[:error] = "You're login credentials are invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private

  def user_params
    params.require(:user).permit(:username,:password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    redirect_back fallback_location: root_path if logged_in?
  end

  def create
    user ||= User.new(user_params)
    if user.save
      flash[:success] = "You have successfully registered to MessageMe"
      session[:user_id] = user.id
      redirect_to root_path
    else
      if User.all.map {|r| r.username}.include?(user.username)
        flash[:error] = "Username has already been taken.."
      elsif user.password != user.password_confirmation
        flash[:error] = "Check your password.. Password mismatch.."
      end
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:username,:password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |message_type,message_content| %>
  <div class="ui <%= message_type %> message">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="active item" href="/">Chatroom</a>
<a class="item">
  Messages
</a>
<div class="right menu">
  <div class="item">
    <% if logged_in? %>
      <%= link_to logout_path, method: :delete, data: {confirm: "Are you sure you want to logout?"}, class: "ui primary button" do %>
        Logout
      <% end %>
    <% else %>
      <a class="ui primary button" href="/login">Login</a>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui massive menu inverted">
      <div class="ui container">
        <%= render 'layouts/navigation'%>
      </div>
    </div>
    <div class="ui container">
      <%= render 'layouts/messages'  %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
       <a><em><%= message.user.username %> : </em></a> <%= message.body %>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular pen square inverted grey icon"></i>
  Say Something...
</h2>

<div class="ui two column grid">

  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form"}, url: 'message', remote: true, id: "cform") do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder: "Type a message.." %>
              <%= f.button "Send", class: "blue ui button"%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui inverted vertical menu">
      <a class="active item">
        Home
      </a>
      <a class="item">
        Messages
      </a>
      <a class="item">
        Friends
      </a>
    </div>
  </div>

</div>

app/views/users/new.html.erb
<h2 class="ui center aligned icon header">
  Welcome to MessageMe - a complete chat app<br><br>
  <i class="circular pen square inverted grey icon"></i>
  Signup to continue
</h2>

<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="middle aligned column">
      <a href="/login">
        <div class="ui big button">
          <i class="signup icon"></i>
          Login
        </div>
      </a>
    </div>
    <div class="column">
      <%= form_for(:user, html: {class: "ui form"}, url: signup_path) do |f| %>
        <div class="field">
          <label>Username</label>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Username", required: true %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <label>Password</label>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "Password", required: true %>
            <i class="lock icon"></i>
          </div>
        </div>
        <div class="field">
          <label>Confirm Password</label>
          <div class="ui left icon input">
            <%= f.password_field :password_confirmation, placeholder: "Confirm password", required: true %>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.submit "Sign Up", class: "ui blue submit button" %>
      <% end %>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>